config:
  SPRING_PROFILES_ACTIVE: "k8s"
  FRONTEND_NOTIFICATION_SERVICE_HOST: "notification-frontend"
  FRONTEND_NOTIFICATION_SERVICE_PASSWORD: ""
  FRONTEND_NOTIFICATION_SERVICE_PORT: "80"
  FRONTEND_NOTIFICATION_SERVICE_SCHEME: "http"
  FRONTEND_NOTIFICATION_SERVICE_USERNAME: ""
