service: certificate-service

container:
  replicas: 1

readinessProbe:
  httpGet:
    path: /admin/health-check
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 5

config:
  JDK_JAVA_OPTIONS: "-XX:MaxRAMPercentage=60.0"

resources:
  requests:
    cpu: 250m
    memory: 2Gi
  limits:
    cpu: 2
    memory: 2Gi

database:
  enabled: false
  migrations:

    enabled: false